### ISSUE TITLE
Adding custom font

### ISSUE THREAD

**Issue by princetonwong** [pymupdf/pymupdf-fonts#2]
I would like to add a custom font. But it shows error.

page.insert_font(fontname="GenJyuuGothicL", fontfile=pathToTTFFont)

x1, y1, x2, y2 = 595 - 33, 0, 595, 842
page.insert_textbox(fitz.Rect(x1 - 20, y1 + 20, x2, y2), some text, fontname="GenJyuuGothicL", fontsize=12, color=someColor, rotate=90, align=2)

It shows this:
TypeError: in method 'Page__insertFont', argument 4 of type 'char *'

**Comment by princetonwong** [comment]
By the way, I need this because of its CJK capacity.

**Comment by JorjMcKie** [comment]
Sorry for the late rreply: I didn't see this, because you posted the bug here. However, you should have used the repo of https://github.com/pymupdf/PyMuPDF, because it has nothing to do with the extra fonts provided in this repo.

I need more info: how did you specify `pathToTTFFont`? If it is not a string, it does not work ...

**Comment by JorjMcKie** [comment]
Another comment:
Using `fitz.Font("cjk")` gives you a font with full combined support of CJK and Latin ...
