### ISSUE TITLE
how to add custom font 

### ISSUE THREAD

**Issue by lomoonmoonbird** [pymupdf/pymupdf-fonts#3]
i use pymupdf to convert pdf to docx, but some font in the pdf doesn't appear on the centos, so it will fail the transfer process,is there any way to add custom font like "Arial". thanks

**Comment by JorjMcKie** [comment]
I am not sure, this issue should be placed here. Probably it is more a "Discussions" item in [here](https://github.com/pymupdf/PyMuPDF/discussions).

But otherwise: how do you convert from PDF to DOCX?
Arial is very close to PDF's Helvetica, but you can of course get hold of some suitable `arial.ttf` in many places online, or use Google's NOTO-SANS.

How to **_integrate_** some file-based font in your app depends however on the app itself ...
